### ISSUE TITLE
rem布局、动画等

### ISSUE THREAD

**Issue by 7986LiChang** [7986LiChang/MerryChristmas#1]
**1. rem相对布局**
- rem布局，相对于根元素html的font-size进行计算。默认情况下，浏览器字体大小16px， 1rem = 16px
- em 布局，相对于父元素的font-size进行计算。会有层级关系的计算。

rem布局的自适应处理：
为了兼容不同的分辨率，需要动态修正跟字体的大小，从而让所有使用rem单位的子元素跟着一起缩放，从而达到自适应的效果。

关键代码：
- 1)事件处理：根据屏幕分辨率调整根元素html的font-size大小
```js
recalc = function(){
     var docEl = document.documentElement;
     docEl.style.font-size = 20 * (docEl.clientWidth / 320) + 'px';
}
```
- 2)事件：
     浏览器窗口大小改变：resize
     设备方向变化（横向持有，纵向持有）：orientationchange
```js
resizeEvt = 'orientationchange' in window ? 'orientationchange' : 'resize';
```
- 3)绑定事件处理：
```js
window.addEventListener(resizeEvt, recalc, false);
document.addEventListener('DOMContentLoaded', recalc, false);
```

**Comment by 7986LiChang** [comment]
**2. 动画效果**
产生动画的常规手段：通过定时器不断切换图片，配合时间，从而产生连续播放模拟动画效果。
以前，实现定时器的效果通过JS，或flash动画，现在通过css3的关键帧动画实现。

- css3 Animation有8个属性：
    animation-name : 动画名     （通过@keyframes animationname {}   指明）
    animation-duration : 动画持续时间
    animation-delay : 延时
    animation-iteration-count : 动画次数
    animation-direction : 方向
    animation-play-state : 控制
    animation-fill-mode : 状态
    animation-timing-function : 时间函数，有个高级的steps()函数

- 使用关键帧动画 + 雪碧图 实现动画效果：根据时间改变雪碧图的位置
1) 首先准备一张雪碧图，例如由三张图合成，每张图大小91*71
![bird](https://user-images.githubusercontent.com/14882636/34032790-8eb3bd78-e1b2-11e7-85c1-4cdd812dcf0b.png)
2) 实现3张图帧动画效果
利用@keyframes 定义动画类，包括动画名称，执行时间，参数等
```css
@keyframes bird-slow{
       0% { background-position-x: -0px; }
      100% { background-position-x: -273px;}
}
```
为元素添加animation，应用动画：
```css
.bird{
       // animation: bird-slow 400ms steps(3) infinite;
       animation-name: bird-slow;
       animation-duration: 400ms;
       animation-timing-function: steps(3);
       animation-iteration-count: infinite;
}
```
其中，steps(3)表示keyframes设置的0%-100%的段中，background-position-x属性值会变化3次，根据steps具体算法，会平分段落值，即：
background-position-x :  0px;
background-position-x : -91px;
background-position-x : -182px
